### ISSUE TITLE
Use the dynamic form in update configuration

### ISSUE THREAD

**Issue by momone83** [simomosi/dynamic-forms#4] opened 2023-03-08 18:56 UTC
Hi @simomosi,
is it possible to make that dependent fields fetch data at startup in case of update?
Obviously if the field on which they depend has a value.

**Comment by simomosi** [comment] 2023-03-08 19:39
Hello @momone83,
yes it's possible. 
[Here](https://simomosi.github.io/dynamic-forms/configurations/rules/#init-rule-configuration) you will find the configuration object.
[Here](https://simomosi.github.io/dynamic-forms/examples/minimal-example/#13-write-the-form-configuration) you will find a working example (look at the 'init' key)

**Comment by momone83** [comment] 2023-03-12 12:17
Hi @simomosi,
thanks, I'm now able to fetch the values of the dependent fields.
How can you make the field show the previously selected value when initializing a dependent dropdown?

**Comment by simomosi** [comment] 2023-03-12 16:02
I understand you want to fetch data on page load and then select a specific value?
In this case there is no out of the box configuration for that because dynamic-forms was designed to handle user interaction.

Try the following code.
```javascript
let isFirstUpdate = true;
const myFirstValue = 1;

let formConfig = {
    /* ... */
    'fields': [
        {
            'name': 'myField',
            /* ... */
            'behavior': {
                'afterUpdate': (htmlElement, data, subjectName) => {
                    if (isFirstUpdate) {
                        setTimeout(() => {
                            htmlElement.value = myFirstValue;
                            htmlElement.dispatchEvent(new Event('change'));
                        }, 1000);
                        isFirstUpdate = false;
                    }
                }
            }
        }
}
```

I know that's a dirty solution.
Don't worry, I'll make an elegant one asap.

**Comment by simomosi** [comment] 2023-03-15 18:52
Hi @momone83,
looking back on it I have some doubts about implementing the requested feature.
As I said dynamic-forms handles user interactions: a form that automatically changes after page load does not suit this purpose.

Furthermore it comes with downsides. Think about different fields connected in series: A updates B, B updates C, C updates D... how long will the user have to wait before having the form ready?

I think the best way to handle this situation is manually loading all fields during page rendering, and using dynamic-forms to handle future interactions.

I hope you understand. Tell me if you need clarifications, otherwise I ask you to close this issue.
Thank you for using dynamic-forms

**Comment by momone83** [comment] 2023-03-16 17:38
Hi @simomosi ,
thank you for your support.
I understand what you mean and it makes sense, but then the init rules would lose their function, don't you think?

I could set only update rules and the form would still work.

**Comment by simomosi** [comment] 2023-03-16 21:04
Yes, you are right.
I have a solution in mind but it could take some time.

I will update you on this issue when it's done

**Comment by simomosi** [comment] 2023-03-24 18:47
Hi @momone83,
I developed the feature you requested.

Please help me testing it before publishing the new version.
You can find it in the [dev branch](https://github.com/simomosi/dynamic-forms/tree/dev) (commit hash `f428fbe`).
Documentation was not yet updated of course, you can find a working example [here](https://github.com/simomosi/dynamic-forms/blob/dev/examples/index.html#L307).

The `init` configuration entry contains objects which identifies:
- fields to initialize
- other values to pass to your server (previously known as `externalData`).

If you specify a value for a field, dynamic-forms will set the value for you.

Please let me know your opinion about dynamic-forms usability and if it works for your use case.

**Closed as completed** 2023-04-14 21:33 UTC
